name: React Tests

on:
  push:
    paths:
      - 'react-app/**'
      - '!react-app/build/**'
  pull_request:
    paths:
      - 'react-app/**'
      - '!react-app/build/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: react-app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: react-app/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npx eslint src --ext .ts,.tsx --max-warnings 0
      continue-on-error: true
    
    - name: Run tests with coverage
      run: npm run test:ci
      env:
        CI: true
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Jest Test Results
        path: 'react-app/test-results/junit.xml'
        reporter: jest-junit
        fail-on-error: false
    
    - name: Coverage Report
      uses: ArtiomTr/jest-coverage-report-action@v2
      if: always()
      with:
        working-directory: react-app
        coverage-file: ./coverage/cobertura-coverage.xml
        base-coverage-file: ./coverage/cobertura-coverage.xml
        threshold: 80
        skip-step: install
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: react-coverage-report
        path: react-app/coverage/
    
    - name: Coverage Summary
      if: always()
      run: |
        echo "### React テストカバレッジ" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| File | Statements | Branches | Functions | Lines |" >> $GITHUB_STEP_SUMMARY
        echo "|------|------------|----------|-----------|-------|" >> $GITHUB_STEP_SUMMARY
        
        # カバレッジサマリーを解析してテーブルに追加
        if [ -f coverage/coverage-summary.json ]; then
          node -e "
            const fs = require('fs');
            const coverage = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8'));
            Object.entries(coverage).forEach(([file, data]) => {
              if (file !== 'total') {
                const fileName = file.replace(/^.*[\\\\/]/, '');
                console.log(\`| \${fileName} | \${data.statements.pct}% | \${data.branches.pct}% | \${data.functions.pct}% | \${data.lines.pct}% |\`);
              }
            });
            if (coverage.total) {
              console.log(\`| **Total** | **\${coverage.total.statements.pct}%** | **\${coverage.total.branches.pct}%** | **\${coverage.total.functions.pct}%** | **\${coverage.total.lines.pct}%** |\`);
            }
          " >> $GITHUB_STEP_SUMMARY
        fi
